const fs = require('fs');

const file = 'server.ts';
let code = fs.readFileSync(file, 'utf8');

const startMarker = 'const seedCircles = [';
const endMarker = 'for (let i = 0; i < richMockData.length; i++) {';

const startIdx = code.indexOf(startMarker);
const endIdx = code.indexOf(endMarker);

if (startIdx !== -1 && endIdx !== -1) {
  const newContent = `const seedCircles = [
        { id: db.collection('circles').doc().id, name: "Techies for Good", description: "Developers and designers giving back.", privacy: "PUBLIC", creatorId: "user_seed_0", isOrganizationLed: false, isSeed: true, createdAt: new Date(), memberCount: 5 },
        { id: db.collection('circles').doc().id, name: "Kreuzberg Dog Walkers", description: "Neighborly help for dog walking.", privacy: "PUBLIC", creatorId: "user_seed_1", isOrganizationLed: false, isSeed: true, createdAt: new Date(), memberCount: 12 },
        { id: db.collection('circles').doc().id, name: "Green Earth Volunteers", description: "Sustainability advocates working on local environmental projects.", privacy: "PUBLIC", creatorId: "org_seed_green_earth", isOrganizationLed: true, isSeed: true, createdAt: new Date(), memberCount: 24 },
        { id: db.collection('circles').doc().id, name: "Neukölln Freegan", description: "Sharing rescued food and tips.", privacy: "PRIVATE", creatorId: "user_seed_6", isOrganizationLed: false, isSeed: true, createdAt: new Date(), memberCount: 30 },
        { id: db.collection('circles').doc().id, name: "Local Artists Connect", description: "Canvas sharing, critiques, and gallery outings.", privacy: "PUBLIC", creatorId: "user_seed_4", isOrganizationLed: false, isSeed: true, createdAt: new Date(), memberCount: 15 },
        { id: db.collection('circles').doc().id, name: "Berlin Bike Fixers", description: "DIY bike maintenance workshops.", privacy: "PUBLIC", creatorId: "user_seed_5", isOrganizationLed: false, isSeed: true, createdAt: new Date(), memberCount: 42 },
        { id: db.collection('circles').doc().id, name: "Prenzlauer Berg Parents", description: "Toy swaps, babysitting exchange, and playground meetups.", privacy: "PUBLIC", creatorId: "user_seed_2", isOrganizationLed: false, isSeed: true, createdAt: new Date(), memberCount: 56 },
        { id: db.collection('circles').doc().id, name: "Tempelhofer Skaters", description: "Inline, roller, and board skaters meeting up at the Feld.", privacy: "PUBLIC", creatorId: "user_seed_3", isOrganizationLed: false, isSeed: true, createdAt: new Date(), memberCount: 89 },
        { id: db.collection('circles').doc().id, name: "Wedding Coders", description: "Study group for web development and pair programming.", privacy: "PRIVATE", creatorId: "user_seed_13", isOrganizationLed: false, isSeed: true, createdAt: new Date(), memberCount: 18 },
        { id: db.collection('circles').doc().id, name: "Moabit Language Cafe", description: "Weekly tandem language exchange in different cafes.", privacy: "PUBLIC", creatorId: "user_seed_7", isOrganizationLed: false, isSeed: true, createdAt: new Date(), memberCount: 35 },
        { id: db.collection('circles').doc().id, name: "Charlottenburg Antiques", description: "Appreciating, restoring, and trading vintage furniture.", privacy: "PUBLIC", creatorId: "user_seed_10", isOrganizationLed: false, isSeed: true, createdAt: new Date(), memberCount: 22 },
        { id: db.collection('circles').doc().id, name: "Friedrichshain Vinyl Swap", description: "Trading records and talking music production.", privacy: "PUBLIC", creatorId: "user_seed_11", isOrganizationLed: false, isSeed: true, createdAt: new Date(), memberCount: 40 }
      ];

      for (const circle of seedCircles) {
        createBatch.set(db.collection('circles').doc(circle.id), circle);
        createBatch.set(db.collection('circles').doc(circle.id).collection('members').doc(circle.creatorId), { joinedAt: new Date() });
      }

      const richMockData = [
        // 12 ASKS
        { title: "Need help carrying a couch up to Altbau 4th floor", description: "I'll provide Club-Mate and pizza for anyone who can spare 20 minutes!", type: "ASK", category: "Service", images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=1000"], status: "ACTIVE", reachTypes: ["VICINITY", "ALL_CIRCLES"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },
        { title: "Anyone have a Schlagbohrmaschine (Hammer Drill)?", description: "Need to install shelves in concrete walls. Happy to bake cookies in return!", type: "ASK", category: "Equipment", images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Drill_scheme.svg/960px-Drill_scheme.svg.png"], status: "ACTIVE", reachTypes: ["ALL_CIRCLES"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },
        { title: "Looking for an old acoustic guitar", description: "Can't afford a new one right now. Can trade web design work!", type: "ASK", category: "Music", images: ["https://upload.wikimedia.org/wikipedia/commons/4/45/GuitareClassique5.png"], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },
        { title: "Borrow: Camping tent for the weekend", description: "Going to the lakes this weekend, looking to borrow a 2-person tent.", type: "ASK", category: "Equipment", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },
        { title: "Need a cat sitter next week", description: "Going away for 5 days. My cat Mimi is very low maintenance.", type: "ASK", category: "Service", images: ["https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=1000"], status: "ACTIVE", reachTypes: ["ALL_CIRCLES", "VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },
        { title: "Looking for a road bike size M", description: "Anyone selling or lending a decent road bike?", type: "ASK", category: "Mobility", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },
        { title: "Seeking a native French speaker for tandem", description: "Offering German or English. Coffee is on me!", type: "ASK", category: "Education", images: [], status: "ACTIVE", reachTypes: ["ALL_CIRCLES"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },
        { title: "Anyone driving to IKEA Lichtenberg?", description: "Need to grab a few small things, would love to join your car ride.", type: "ASK", category: "Mobility", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },
        { title: "Need tips on repotting a large Monstera", description: "It's getting huge and I'm afraid to damage it. Anyone experienced who can come over and help?", type: "ASK", category: "Service", images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Monstera_deliciosa2.jpg/960px-Monstera_deliciosa2.jpg"], status: "ACTIVE", reachTypes: ["VICINITY", "SPECIFIC_CIRCLES"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },
        { title: "Looking for moving boxes ASAP", description: "Moving this weekend and underestimated my stuff. Need 10-15 boxes.", type: "ASK", category: "Equipment", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },
        { title: "Can someone format my old Windows laptop?", description: "I want to install Ubuntu but I'm tech illiterate.", type: "ASK", category: "Service", images: [], status: "ACTIVE", reachTypes: ["ALL_CIRCLES"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },
        { title: "Borrow: projector for movie night", description: "Just for Saturday. I'll leave a deposit if needed.", type: "ASK", category: "Equipment", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_1', userName: 'Bob Miller', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob%20Miller', content: 'I am interested!', createdAt: new Date() }] },

        // 12 SHARES
        { title: "Leftover fresh pastries from my bakery", description: "3 boxes of fresh croissants and muffins. First come, first served!", type: "SHARE", category: "Food", images: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1000"], status: "ACTIVE", reachTypes: ["VICINITY"], isFeatured: false, expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },
        { title: "Vintage FujiFilm Camera & Film", description: "Upgraded, so giving away my X-T10. Hoping it finds a photography learner!", type: "SHARE", category: "Electronics", images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=1000"], status: "ACTIVE", reachTypes: ["VICINITY"], isFeatured: true, expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },
        { title: "Book Exchange: Sci-Fi & Fantasy", description: "Pile of sci-fi and fantasy books to swap. Bring what you've finished reading!", type: "SHARE", category: "Books", images: ["https://images.unsplash.com/photo-1510915361894-db8b60106cb1?q=80&w=1000"], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },
        { title: "Monstera cuttings ready for propagation", description: "They've been rooting in water. Ready for soil now. Bring a small pot.", type: "SHARE", category: "Plants", images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Monstera_deliciosa2.jpg/960px-Monstera_deliciosa2.jpg"], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },
        { title: "Giving away moving boxes", description: "Around 15 sturdy Banana boxes. Perfect for moving.", type: "SHARE", category: "Home", images: [], status: "ACTIVE", reachTypes: ["ALL_CIRCLES", "VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },
        { title: "Home-grown tomatoes", description: "My balcony garden exploded. Giving away 2kg of cherry tomatoes.", type: "SHARE", category: "Food", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },
        { title: "IKEA desk chair (Marcus), perfectly fine", description: "Got a new ergonomic one. This one still works great. Free to pickup.", type: "SHARE", category: "Furniture", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },
        { title: "Free sourdough starter (Herman)", description: "My starter has grown too much. Giving away portions to fellow bakers.", type: "SHARE", category: "Food", images: [], status: "ACTIVE", reachTypes: ["VICINITY", "SPECIFIC_CIRCLES"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },
        { title: "Baby clothes 0-6 months, like new", description: "Washed and folded. One large bag full.", type: "SHARE", category: "Clothing", images: [], status: "ACTIVE", reachTypes: ["VICINITY", "ALL_CIRCLES"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },
        { title: "Giving away my old acoustic guitar", description: "Has a few scratches but plays well. Strings are new.", type: "SHARE", category: "Music", images: ["https://upload.wikimedia.org/wikipedia/commons/4/45/GuitareClassique5.png"], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },
        { title: "Extra tickets (2) for the outdoor cinema tonight", description: "Can't make it to Freiluftkino Kreuzberg tonight. First one gets the QR codes.", type: "SHARE", category: "Events", images: [], status: "ACTIVE", reachTypes: ["ALL_CIRCLES"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },
        { title: "Kefir grains", description: "Healthy water kefir grains, multiply super fast. Bring a jar.", type: "SHARE", category: "Food", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], expiresAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 5), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_2', userName: 'Chloe Smith', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe%20Smith', content: 'Is this still available?', createdAt: new Date() }, { id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_3', userName: 'David Park', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David%20Park', content: 'Would love to take this!', createdAt: new Date() }] },

        // 8 IMECES
        { title: "Tempelhofer Feld Cleanup", description: "Full day cleanup of the grill area. Trash bags provided.", type: "IMECE", category: "Environment", images: ["https://upload.wikimedia.org/wikipedia/commons/2/2e/Community_garden_in_Ottawa.jpg"], status: "ACTIVE", reachTypes: ["VICINITY"], neededParticipants: 10, isFeatured: true, eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Street Art Mural Painting at Mauerpark", description: "Need 15 volunteers to help block out colors. No experience needed!", type: "IMECE", category: "Art", images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Capitole_Toulouse_-_Salle_des_Illustres_-_Toulouse_coop%C3%A9rant_%C3%A0_la_d%C3%A9fense_nationale_1897_-_Jean-Andr%C3%A9_Rixens.jpg/960px-Capitole_Toulouse_-_Salle_des_Illustres_-_Toulouse_coop%C3%A9rant_%C3%A0_la_d%C3%A9fense_nationale_1897_-_Jean-Andr%C3%A9_Rixens.jpg"], status: "ACTIVE", reachTypes: ["VICINITY", "ALL_CIRCLES"], neededParticipants: 15, isFeatured: true, eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Community Garden Spring Prep", description: "We need hands to turn soil and plant seeds for the local garden.", type: "IMECE", category: "Environment", images: [], status: "ACTIVE", reachTypes: ["VICINITY", "SPECIFIC_CIRCLES"], neededParticipants: 8, eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Repair Cafe Pop-up Weekend", description: "Fixing electronics and bikes together. Bring your broken things or your tools.", type: "IMECE", category: "Community", images: [], status: "ACTIVE", reachTypes: ["ALL_CIRCLES"], neededParticipants: 5, eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Neighborhood Block Party Setup", description: "We got the permit! Need help setting up tables, string lights, and seating.", type: "IMECE", category: "Events", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], neededParticipants: 12, eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Painting the local youth center", description: "The walls need a fresh coat of white. Paint and rollers provided by the city.", type: "IMECE", category: "Community", images: [], status: "ACTIVE", reachTypes: ["ALL_CIRCLES", "VICINITY"], neededParticipants: 6, eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Making sandwiches for the homeless shelter", description: "Everyone brings one ingredient, we assemble 200 sandwiches together.", type: "IMECE", category: "Support", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], neededParticipants: 8, eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Guerilla Gardening: Seed Bombing", description: "Let's throw some wildflowers onto the traffic islands near the station.", type: "IMECE", category: "Environment", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], neededParticipants: 4, eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },

        // 8 MISSIONS (Org Led)
        { title: "Winter clothing drive for local shelter", description: "Collect winter parkas for local shelters. Help sort or drive donations.", type: "MISSION", category: "Community", images: ["https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Schneewanne01.jpg/960px-Schneewanne01.jpg"], status: "ACTIVE", reachTypes: ["VICINITY", "ALL_CIRCLES"], neededParticipants: 20, isFeatured: true, orgOwner: "org_seed_kiez_helpers", eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Food Rescue Drive", description: "Pick up food from 15 bakeries at closing time to redistribute.", type: "MISSION", category: "Community", images: [], status: "ACTIVE", reachTypes: ["ALL_CIRCLES"], neededParticipants: 10, orgOwner: "org_seed_food_saver", eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Tree Planting Initiative 2026", description: "Help us plant 500 saplings in the outskirt forests this weekend.", type: "MISSION", category: "Environment", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], neededParticipants: 50, orgOwner: "org_seed_green_earth", eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Refugee Welcome Kits Assembly", description: "Assembling hygiene kits and welcome guides. Need 30 hands.", type: "MISSION", category: "Support", images: [], status: "ACTIVE", reachTypes: ["ALL_CIRCLES", "VICINITY"], neededParticipants: 30, orgOwner: "org_seed_community_builders", eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Laptop repair workshop for refugees", description: "If you know how to wipe and reinstall an OS, we need you to prep 40 donated laptops.", type: "MISSION", category: "Education", images: [], status: "ACTIVE", reachTypes: ["ALL_CIRCLES"], neededParticipants: 10, orgOwner: "org_seed_tech_refugees", eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Dog walking at the local shelter", description: "The shelter is overflowing. We need experienced dog handlers for morning walks.", type: "MISSION", category: "Community", images: [], status: "ACTIVE", reachTypes: ["VICINITY", "ALL_CIRCLES"], neededParticipants: 15, orgOwner: "org_seed_berlin_strays", eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Soup Kitchen Sunday Service", description: "Prep, cook, serve, and clean up. We serve 300 warm meals.", type: "MISSION", category: "Support", images: [], status: "ACTIVE", reachTypes: ["VICINITY"], neededParticipants: 12, orgOwner: "org_seed_kiez_helpers", eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] },
        { title: "Urban park cleaning marathon", description: "We are tackling 5 parks in one day. Great workout, great karma.", type: "MISSION", category: "Environment", images: [], status: "ACTIVE", reachTypes: ["ALL_CIRCLES"], neededParticipants: 40, orgOwner: "org_seed_green_earth", eventTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3), eventEndTime: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 60 * 2), comments: [{ id: 'c_' + Math.random().toString(36).substr(2, 9), userId: 'user_seed_4', userName: 'Emma Wagner', userPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma%20Wagner', content: 'Count me in.', createdAt: new Date() }] }
      ];

      const berlinLocations = [
        { label: "Mitte", lat: 52.5200, lng: 13.4050 },
        { label: "Kreuzberg", lat: 52.4984, lng: 13.3942 },
        { label: "Neukölln", lat: 52.4811, lng: 13.4354 },
        { label: "Friedrichshain", lat: 52.5158, lng: 13.4540 },
        { label: "Prenzlauer Berg", lat: 52.5388, lng: 13.4246 },
        { label: "Schöneberg", lat: 52.4826, lng: 13.3541 },
        { label: "Charlottenburg", lat: 52.5160, lng: 13.3039 },
        { label: "Wedding", lat: 52.5501, lng: 13.3364 },
        { label: "Moabit", lat: 52.5298, lng: 13.3377 },
        { label: "Spandau", lat: 52.5367, lng: 13.1973 },
        { label: "Steglitz", lat: 52.4552, lng: 13.3220 },
        { label: "Zehlendorf", lat: 52.4332, lng: 13.2592 },
        { label: "Tempelhof", lat: 52.4646, lng: 13.3857 },
        { label: "Treptow", lat: 52.4870, lng: 13.4682 },
        { label: "Köpenick", lat: 52.4452, lng: 13.5786 },
        { label: "Marzahn", lat: 52.5414, lng: 13.5583 },
        { label: "Hellersdorf", lat: 52.5366, lng: 13.6063 },
        { label: "Lichtenberg", lat: 52.5167, lng: 13.4833 },
        { label: "Reinickendorf", lat: 52.5765, lng: 13.3444 }
      ];

      `;
  
  const modified = code.substring(0, startIdx) + newContent + code.substring(endIdx);
  fs.writeFileSync(file, modified);
  console.log("Success phase 2");
} else {
  console.error("Markers not found");
}
