// Items for profiles u1-u10. Each has 3 SHARE, 3 ASK, 1 IMECE with comments.
export const items1 = [
  // u1 Marta
  { title:"Sourdough Starter (3yr old)", desc:"Grandmother's recipe, very active. Happy to share a jar!", type:"SHARE", cat:"Food", owner:"u1", img:"https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=400", comments:[{uid:"u5",text:"Is it hard to keep alive? I killed my last one."},{uid:"u9",text:"I'd love some! Will trade for French herbs."}] },
  { title:"Homemade Kombucha Bottles", desc:"Brewed weekly. Ginger-lemon and berry flavors available.", type:"SHARE", cat:"Food", owner:"u1", img:"https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=400", comments:[{uid:"u18",text:"Does it pair well with espresso? Asking for science."},{uid:"u11",text:"I'd love the ginger one! Great for digestion."}] },
  { title:"Garden Tool Set (weekend loan)", desc:"Spade, rake, pruners, wheelbarrow. Pick up Saturday morning.", type:"SHARE", cat:"Tools", owner:"u1", comments:[{uid:"u16",text:"Perfect timing, I need the wheelbarrow for the raised beds."},{uid:"u4",text:"Can I borrow the pruners for my balcony roses?"}] },
  { title:"Need a bike trailer", desc:"Looking to borrow a bike trailer to haul compost from the garden.", type:"ASK", cat:"Transport", owner:"u1", comments:[{uid:"u6",text:"I have one! DM me to arrange pickup."},{uid:"u10",text:"I can lend mine on weekdays, it's at the bike kitchen."}] },
  { title:"Cat sitter for a long weekend", desc:"My cat Miso needs feeding and company, Fri–Sun. Very friendly.", type:"ASK", cat:"Pets", owner:"u1", comments:[{uid:"u8",text:"I love cats. Happy to help if the dates work."},{uid:"u3",text:"Miso is adorable! I can do Saturday if needed."}] },
  { title:"Borrowing a dehydrator", desc:"Want to dry herbs and fruit from the garden. Anyone have one?", type:"ASK", cat:"Kitchen", owner:"u1", comments:[{uid:"u14",text:"I have a small one. Works great for mushrooms too."},{uid:"u5",text:"I've been wanting to try this! Let me know how it goes."}] },
  { title:"Community Garden Spring Cleanup", desc:"Let's get the Boxhagener plots ready for planting season! Tools and gloves provided.", type:"IMECE", cat:"Garden", owner:"u1", circleId:"c_garden", comments:[{uid:"u16",text:"I'll bring my truck for the heavy mulch bags."},{uid:"u5",text:"Count me in! I'll make lemonade for everyone."},{uid:"u13",text:"Can I bring the kids? They love digging."}] },

  // u2 Lukas
  { title:"Cordless Drill Set", desc:"Bosch 18V with bits for wood, metal, and masonry.", type:"SHARE", cat:"Tools", owner:"u2", img:"https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400", comments:[{uid:"u4",text:"Is it SDS-plus? Need it for Altbau walls."},{uid:"u16",text:"Lifesaver. Can I grab it Thursday evening?"}] },
  { title:"Workbench Access (weekends)", desc:"My garage workshop is open Sat/Sun. Clamps, vise, hand tools included.", type:"SHARE", cat:"Workshop", owner:"u2", comments:[{uid:"u10",text:"Could I use it to rebuild a bike frame?"},{uid:"u19",text:"Would love to use it for a sewing table project."}] },
  { title:"Reclaimed Wood Pieces", desc:"Leftover oak and pine from renovation jobs. Various sizes.", type:"SHARE", cat:"Materials", owner:"u2", comments:[{uid:"u16",text:"The oak would be perfect for cutting boards!"},{uid:"u17",text:"Can I have some for an art installation?"}] },
  { title:"Plumbing help for bathroom", desc:"Slow drain and a dripping faucet. Happy to trade carpentry work.", type:"ASK", cat:"Home", owner:"u2", comments:[{uid:"u4",text:"Sounds like a washer issue. I'll come look."},{uid:"u10",text:"I fixed mine with a YouTube video, want the link?"}] },
  { title:"Vintage cabinet restoration tips", desc:"Found a 1920s Schrank at the flea market. Need advice on finish.", type:"ASK", cat:"Furniture", owner:"u2", comments:[{uid:"u16",text:"Shellac and wax. Never polyurethane on antiques."},{uid:"u20",text:"My nonno had the same style! Beautiful find."}] },
  { title:"Extra moving boxes needed", desc:"Helping a friend move next week. Need 15-20 sturdy boxes.", type:"ASK", cat:"Household", owner:"u2", comments:[{uid:"u8",text:"I have about 10 from my last move. Yours to take."},{uid:"u15",text:"Check the Späti on Weserstr, they always have some."}] },
  { title:"Playground Bench Repair Day", desc:"The benches at Boxhagener Platz are falling apart. Let's fix them together!", type:"IMECE", cat:"Community", owner:"u2", circleId:"c_fixit", comments:[{uid:"u4",text:"I'll handle the electrical if any lights need fixing."},{uid:"u10",text:"Count me in. Bringing my toolbox."}] },

  // u3 Aya
  { title:"Yoga Mat and Blocks", desc:"Spare set in great condition. Good for beginners.", type:"SHARE", cat:"Fitness", owner:"u3", comments:[{uid:"u11",text:"Perfect for my prenatal clients! Can I pick up tomorrow?"},{uid:"u15",text:"I'd love these for my home practice."}] },
  { title:"Watercolor Paint Set", desc:"Winsor & Newton cotman set, barely used. 24 colors.", type:"SHARE", cat:"Art", owner:"u3", comments:[{uid:"u17",text:"Amazing brand! Would love to trade for some manga markers."},{uid:"u8",text:"I've been wanting to try watercolors for ages."}] },
  { title:"Japanese Tea Ceremony Set", desc:"Matcha bowl, whisk, and scoop. Happy to demo the ceremony.", type:"SHARE", cat:"Culture", owner:"u3", comments:[{uid:"u14",text:"Beautiful set! Reminds me of home."},{uid:"u9",text:"Can we do a tea and pastry pairing session?"}] },
  { title:"Quiet studio space afternoons", desc:"Looking for a calm space to paint 2-3 afternoons a week.", type:"ASK", cat:"Space", owner:"u3", comments:[{uid:"u16",text:"My workshop has a back room with north light. Let's talk."},{uid:"u7",text:"The music school has free rooms on Tuesdays."}] },
  { title:"Life drawing model needed", desc:"Starting a figure drawing group. Need a volunteer model.", type:"ASK", cat:"Art", owner:"u3", comments:[{uid:"u15",text:"I'd be happy to model! Dancer's body, used to it."},{uid:"u17",text:"I can help organize this at the art collective space."}] },
  { title:"Meditation group to join", desc:"Looking for a regular sit, any tradition. Weekly preferred.", type:"ASK", cat:"Wellness", owner:"u3", comments:[{uid:"u11",text:"I host a small circle Tuesday evenings. Herbal tea included."},{uid:"u14",text:"I practice Zen sitting. Happy to share the discipline."}] },
  { title:"Free Yoga at Tempelhofer Feld", desc:"Sunday morning flow for all levels. Bring your own mat. Meet at the Schillerkiez entrance.", type:"IMECE", cat:"Wellness", owner:"u3", comments:[{uid:"u5",text:"This is wonderful! I'll spread the word."},{uid:"u12",text:"Can I bring the football kids for stretching after practice?"}] },

  // u4 Sven
  { title:"Electrical Testing Multimeter", desc:"Fluke multimeter for checking outlets, wiring, continuity.", type:"SHARE", cat:"Tools", owner:"u4", comments:[{uid:"u6",text:"Need this for a home server install. Available this week?"},{uid:"u2",text:"Sven, you're a legend. Can I borrow it Saturday?"}] },
  { title:"Free Chess Lessons", desc:"Retired and looking for students. All levels welcome, my place or park.", type:"SHARE", cat:"Education", owner:"u4", comments:[{uid:"u12",text:"My son has been begging for chess lessons!"},{uid:"u13",text:"I haven't played since university. Would love a refresher."}] },
  { title:"Vintage Radio Repair", desc:"I fix old tube radios. Bring me your broken Grundig or Telefunken.", type:"SHARE", cat:"Repair", owner:"u4", comments:[{uid:"u20",text:"I have a gorgeous broken Grundig! When can I bring it?"},{uid:"u7",text:"Can you look at my old amplifier too?"}] },
  { title:"Help setting up smartphone", desc:"New phone, no idea how to use it. Patient teacher needed.", type:"ASK", cat:"Tech", owner:"u4", comments:[{uid:"u6",text:"I'll come over with coffee. We'll set it up in an hour."},{uid:"u17",text:"Happy to help! I made a simple guide for my grandmother too."}] },
  { title:"Chess partner for Sunday mornings", desc:"Looking for a regular opponent. Boxhagener Platz, 10am.", type:"ASK", cat:"Social", owner:"u4", comments:[{uid:"u8",text:"I'm rusty but willing! See you at the benches."},{uid:"u14",text:"I play shogi but would love to learn chess strategy."}] },
  { title:"Advice on balcony herb garden", desc:"Want to grow herbs but my balcony is mostly shade. Tips?", type:"ASK", cat:"Garden", owner:"u4", comments:[{uid:"u1",text:"Mint and chives thrive in shade! I'll bring you starters."},{uid:"u11",text:"Lemon balm is perfect for shade and makes great tea."}] },
  { title:"Rewiring the Community Center", desc:"The Nachbarschaftszentrum needs new wiring. I'll lead, need helpers to run cable.", type:"IMECE", cat:"Infrastructure", owner:"u4", circleId:"c_fixit", comments:[{uid:"u2",text:"I'll drill the channels. Saturday works?"},{uid:"u6",text:"I can help after 2pm. Bringing cable clips."}] },

  // u5 Elena
  { title:"Fresh Sourdough Loaves (Saturdays)", desc:"I bake 6 loaves every Saturday. First come, first served at my door.", type:"SHARE", cat:"Food", owner:"u5", img:"https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400", comments:[{uid:"u1",text:"Your bread is the best in the Kiez, hands down."},{uid:"u20",text:"Can I trade a jar of my nonna's tomato sauce for a loaf?"}] },
  { title:"Complete Baking Tin Set", desc:"Bundt, loaf, muffin, springform. All good quality, rarely used.", type:"SHARE", cat:"Kitchen", owner:"u5", comments:[{uid:"u9",text:"The springform would be perfect for my tarte tatin!"},{uid:"u18",text:"Could I borrow the muffin tin for a coffee morning batch?"}] },
  { title:"Garden Plot Time Sharing", desc:"I have more plot than I can use. Want to share a section?", type:"SHARE", cat:"Garden", owner:"u5", comments:[{uid:"u13",text:"I'd love to grow some sunflowers with my reading group kids."},{uid:"u16",text:"Tomatoes! I'll build a proper trellis for them."}] },
  { title:"Stand mixer to borrow", desc:"Mine broke mid-batch. Need one for this weekend's baking.", type:"ASK", cat:"Kitchen", owner:"u5", comments:[{uid:"u9",text:"You can use mine! It's a KitchenAid, works beautifully."},{uid:"u14",text:"I have a hand mixer if the KitchenAid is taken."}] },
  { title:"Farmers market vendor contacts", desc:"Want to sell preserves at the weekly market. Who do I talk to?", type:"ASK", cat:"Business", owner:"u5", comments:[{uid:"u18",text:"I know the organizer! I'll connect you over coffee."},{uid:"u1",text:"Talk to the honey stand lady, she knows everyone."}] },
  { title:"Help organizing a block party", desc:"Planning a summer Hoffest. Need help with logistics, music, and food.", type:"ASK", cat:"Events", owner:"u5", comments:[{uid:"u7",text:"I'll organize the live music! Quartet available."},{uid:"u12",text:"Football skills booth for the kids? I'm in."}] },
  { title:"Sunday Community Brunch", desc:"Monthly Hinterhof brunch. Everyone brings a dish. Tables, coffee, and music provided.", type:"IMECE", cat:"Community", owner:"u5", comments:[{uid:"u9",text:"I'll make quiche lorraine! How many people expected?"},{uid:"u20",text:"Bringing fresh pasta and Aperol Spritz."},{uid:"u7",text:"I'll play background piano if there's power outside."}] },

  // u6 Faisal
  { title:"Old ThinkPad for Learning", desc:"T440p, works fine. Linux installed. Great for kids or beginners.", type:"SHARE", cat:"Electronics", owner:"u6", comments:[{uid:"u12",text:"My nephew could really use this for school."},{uid:"u17",text:"Would be perfect for my illustration side projects!"}] },
  { title:"Bicycle Repair Toolkit", desc:"Allen keys, tire levers, chain tool, spoke wrench. Full portable kit.", type:"SHARE", cat:"Tools", owner:"u6", comments:[{uid:"u10",text:"Good kit! Want to co-host a repair workshop?"},{uid:"u12",text:"Can I borrow the spoke wrench? My back wheel wobbles."}] },
  { title:"Free Coding Tutoring", desc:"Python, JavaScript, basics of web dev. 1hr sessions, any age.", type:"SHARE", cat:"Education", owner:"u6", comments:[{uid:"u4",text:"Could you teach me to make a simple website?"},{uid:"u17",text:"I want to learn to code my illustration portfolio. Yes please!"}] },
  { title:"Standing desk for home office", desc:"WFH is killing my back. Looking for an affordable sit-stand desk.", type:"ASK", cat:"Furniture", owner:"u6", comments:[{uid:"u2",text:"I can build you one from reclaimed wood. Seriously."},{uid:"u16",text:"IKEA Bekant goes on sale often. I'll watch for you."}] },
  { title:"Running partner, mornings", desc:"Training for a half marathon. Looking for 6am company, any pace.", type:"ASK", cat:"Fitness", owner:"u6", comments:[{uid:"u12",text:"6am is early but I'm in! Volkspark route?"},{uid:"u3",text:"I run at 7. Close enough?"}] },
  { title:"Help assembling IKEA furniture", desc:"Bought a whole apartment's worth. Pizza and beer for helpers.", type:"ASK", cat:"Home", owner:"u6", comments:[{uid:"u2",text:"This is literally my hobby. When do we start?"},{uid:"u10",text:"I'll bring my power driver. Makes it 10x faster."}] },
  { title:"Free Coding Workshop for Kids", desc:"Teaching neighborhood kids the basics of programming. Laptops provided. Ages 10-16.", type:"IMECE", cat:"Education", owner:"u6", circleId:"c_tech", comments:[{uid:"u12",text:"Signing up 4 kids from the football team!"},{uid:"u17",text:"I can help teach the design/visual side."},{uid:"u4",text:"Can old people come too? Asking for myself."}] },

  // u7 Greta
  { title:"Piano Practice Hours", desc:"My piano is free weekday mornings. Come practice at my place.", type:"SHARE", cat:"Music", owner:"u7", comments:[{uid:"u15",text:"I need to rehearse for a performance. Tuesday mornings?"},{uid:"u9",text:"I haven't played since childhood. Can I just come noodle?"}] },
  { title:"Music Theory Books", desc:"Complete collection of Berklee textbooks. Harmony, ear training, composition.", type:"SHARE", cat:"Education", owner:"u7", comments:[{uid:"u20",text:"The harmony book would help my DJ mixing. Can I borrow?"},{uid:"u12",text:"My daughter just started trumpet. The ear training book would help!"}] },
  { title:"Spare Acoustic Guitar", desc:"Yamaha FG800. Solid top, great sound. Needs a good home.", type:"SHARE", cat:"Music", owner:"u7", img:"https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400", comments:[{uid:"u3",text:"I've always wanted to learn guitar. Can I have it?"},{uid:"u8",text:"That's a great beginner guitar. Very generous of you."}] },
  { title:"Help moving upright piano", desc:"Moving from 3rd floor to ground floor. Need 3-4 strong people.", type:"ASK", cat:"Moving", owner:"u7", comments:[{uid:"u10",text:"I have a dolly and the arms. Count me in."},{uid:"u2",text:"I'll bring straps and my van. Saturday work?"}] },
  { title:"Vocalist for chamber quartet", desc:"We play local venues and need a soprano or alto voice.", type:"ASK", cat:"Music", owner:"u7", comments:[{uid:"u15",text:"I sing alto! Let's do an audition over tea."},{uid:"u9",text:"I sing French chanson, if that's your vibe?"}] },
  { title:"Affordable rehearsal space", desc:"Looking for a quiet room, 2-3 evenings/week. Can share with others.", type:"ASK", cat:"Space", owner:"u7", comments:[{uid:"u16",text:"Church on Lausitzer has a basement room. €30/month."},{uid:"u6",text:"The tech co-working has a soundproofed room. I'll ask."}] },
  { title:"Street Music Festival", desc:"Organizing a one-day music fest on our block. Performers, sound help, and audience needed!", type:"IMECE", cat:"Culture", owner:"u7", circleId:"c_music", comments:[{uid:"u20",text:"I'll DJ the afternoon slot! Vinyl only, of course."},{uid:"u15",text:"Salsa performance at sunset? Yes please."}] },

  // u8 Henry
  { title:"50mm Camera Lens Loan", desc:"Canon EF 50mm f/1.8. Sharp and fast. Great for portraits.", type:"SHARE", cat:"Photography", owner:"u8", img:"https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400", comments:[{uid:"u17",text:"Perfect for reference photos for my illustrations!"},{uid:"u3",text:"I'd love to photograph the yoga sessions with this."}] },
  { title:"Proofreading and Editing", desc:"Native English speaker. Happy to proofread CVs, letters, essays.", type:"SHARE", cat:"Skills", owner:"u8", comments:[{uid:"u14",text:"Could you check my restaurant menu English?"},{uid:"u6",text:"Need help with a cover letter for a Berlin startup."}] },
  { title:"Photography Technique Books", desc:"Lighting, composition, darkroom. Mix of classic and modern.", type:"SHARE", cat:"Books", owner:"u8", comments:[{uid:"u13",text:"Would love these for the street library collection!"},{uid:"u3",text:"The composition book sounds perfect for my painting."}] },
  { title:"German document translation", desc:"Expat struggling with Behörde letters. Patient translator needed.", type:"ASK", cat:"Language", owner:"u8", comments:[{uid:"u4",text:"Bring them over. I'll translate over coffee."},{uid:"u11",text:"I can help with medical documents specifically."}] },
  { title:"Writing critique group", desc:"Looking for 3-4 people to swap manuscripts and give honest feedback.", type:"ASK", cat:"Creative", owner:"u8", comments:[{uid:"u13",text:"Yes! I've been looking for exactly this."},{uid:"u7",text:"I write lyrics. Does that count?"}] },
  { title:"Darkroom access", desc:"Want to develop film. Anyone have a darkroom or know a shared one?", type:"ASK", cat:"Photography", owner:"u8", comments:[{uid:"u17",text:"There's one at Fotolabor in Kreuzberg. €5/session."},{uid:"u3",text:"I'd love to learn darkroom printing too!"}] },
  { title:"Neighborhood Photo Documentation", desc:"Let's photograph every courtyard, shopfront, and character in our Kiez before they change.", type:"IMECE", cat:"Culture", owner:"u8", circleId:"c_art", comments:[{uid:"u17",text:"I'll illustrate some of the portraits! Collaboration?"},{uid:"u13",text:"The library can host an exhibition of the final work."}] },

  // u9 Sophie
  { title:"French Cooking Lesson", desc:"Learn to make ratatouille, crêpes, or coq au vin. My kitchen, your appetite.", type:"SHARE", cat:"Food", owner:"u9", img:"https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400", comments:[{uid:"u20",text:"Crêpes! Can we do a French-Italian dinner collab?"},{uid:"u5",text:"I'd bring my sourdough to go with the ratatouille!"}] },
  { title:"Fresh Herb Garden Cuttings", desc:"Rosemary, thyme, sage, tarragon. Ready to pot and grow.", type:"SHARE", cat:"Garden", owner:"u9", comments:[{uid:"u1",text:"Tarragon! Yes please. I'll trade for mint cuttings."},{uid:"u11",text:"Sage is wonderful for smudging too. I'd love some."}] },
  { title:"Vintage French Cookbooks", desc:"Julia Child, Escoffier, and more. In French and English.", type:"SHARE", cat:"Books", owner:"u9", comments:[{uid:"u13",text:"The Escoffier would be a jewel for the book club!"},{uid:"u14",text:"Julia Child changed how I approach cooking. Great collection."}] },
  { title:"Food truck vendor contacts", desc:"Thinking of starting a weekend crêpe stand. Who runs the market?", type:"ASK", cat:"Business", owner:"u9", comments:[{uid:"u18",text:"Let's team up! Coffee and crêpes = gold."},{uid:"u5",text:"The Maybachufer market manager is a friend. I'll introduce you."}] },
  { title:"Commercial kitchen rental", desc:"Need a licensed kitchen for catering prep. A few hours weekly.", type:"ASK", cat:"Space", owner:"u9", comments:[{uid:"u14",text:"The Japanese restaurant is empty Tuesday mornings."},{uid:"u18",text:"My roastery has a small kitchen. Come look at it."}] },
  { title:"Help writing a business plan", desc:"French cuisine catering startup. Need help with the numbers side.", type:"ASK", cat:"Business", owner:"u9", comments:[{uid:"u6",text:"I've helped 3 friends with business plans. Let's meet."},{uid:"u16",text:"I can help with the cost projections."}] },
  { title:"Pop-up Dinner for 20 Neighbors", desc:"Three-course French dinner in our Hinterhof. Bring wine, bring friends. Pay what you can.", type:"IMECE", cat:"Food", owner:"u9", circleId:"c_cooking", comments:[{uid:"u20",text:"I'll bring Italian wine and help with dessert."},{uid:"u1",text:"I'll make sourdough rolls for the table!"},{uid:"u14",text:"Can I contribute a Japanese amuse-bouche?"}] },

  // u10 Jakob
  { title:"Bosch Hammer Drill", desc:"SDS-plus, 800W. Eats through concrete. Bits included.", type:"SHARE", cat:"Tools", owner:"u10", img:"https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400", comments:[{uid:"u2",text:"Is this the GBH 2-26? Beast of a machine."},{uid:"u4",text:"Need it for the community center. Can I borrow Monday?"}] },
  { title:"Bike Pump and Patch Kit", desc:"Floor pump and a full patch kit with spare tubes.", type:"SHARE", cat:"Cycling", owner:"u10", comments:[{uid:"u6",text:"Can I keep it at the bike kitchen for communal use?"},{uid:"u12",text:"Just got a flat. You're a lifesaver."}] },
  { title:"Car Jack and Tire Tools", desc:"Hydraulic jack, lug wrench, torque wrench. For any car.", type:"SHARE", cat:"Automotive", owner:"u10", comments:[{uid:"u2",text:"Need to change my van tires. Available this weekend?"},{uid:"u16",text:"Perfect, my car has been sitting on a flat for a week."}] },
  { title:"Engine diagnostic scanner", desc:"Check engine light on. Need an OBD2 scanner to read codes.", type:"ASK", cat:"Automotive", owner:"u10", comments:[{uid:"u6",text:"I have a Bluetooth one. Works with a phone app."},{uid:"u4",text:"Autozone used to lend them. Not sure about Berlin though."}] },
  { title:"Garage space for weekend project", desc:"Rebuilding a vintage moped. Need covered space for a few weekends.", type:"ASK", cat:"Space", owner:"u10", comments:[{uid:"u2",text:"My garage has room. Bring beer and you're welcome."},{uid:"u16",text:"The Hinterhof storage room might work too."}] },
  { title:"Welding class recommendation", desc:"Want to learn MIG welding for bike frame building.", type:"ASK", cat:"Skills", owner:"u10", comments:[{uid:"u16",text:"Helle Nebelung in Wedding has great courses."},{uid:"u2",text:"I took one at Maker Space Berlin. Solid basics."}] },
  { title:"Free Bicycle Repair Workshop", desc:"Bring your broken bike. Tools, parts, and guidance provided. All skill levels.", type:"IMECE", cat:"Transport", owner:"u10", circleId:"c_bikes", comments:[{uid:"u6",text:"I'll handle the gear and brake adjustments station."},{uid:"u12",text:"Bringing 3 bikes from the youth football team!"},{uid:"u2",text:"I can teach tire and tube repairs."}] },
];
