// Items for profiles u11-u20. Each has 3 SHARE, 3 ASK, 1 JOIN with comments.
export const items2 = [
  // u11 Lena
  { title:"Herbal Tea Collection", desc:"Hand-picked herbs from the countryside. Chamomile, peppermint, and elderberry.", type:"SHARE", cat:"Food", owner:"u11", comments:[{uid:"u5",text:"The elderberry tea is amazing for colds!"},{uid:"u1",text:"Would love some chamomile for the garden meetup."}] },
  { title:"Baby Clothes (0-6 months)", desc:"Gender-neutral organic cotton. Gently used.", type:"SHARE", cat:"Kids", owner:"u11", img:"https://images.unsplash.com/photo-1522771935876-2497116a7a9e?w=400", comments:[{uid:"u8",text:"We have a newborn on the way, could we take these?"},{uid:"u15",text:"Beautiful quality! Lena is the best midwife."}] },
  { title:"Guided Forest Foraging Walk", desc:"Learn to identify edible mushrooms and berries. Saturday morning.", type:"SHARE", cat:"Education", owner:"u11", comments:[{uid:"u1",text:"I've always been too scared to pick mushrooms. Yes please!"},{uid:"u9",text:"I can show how to cook whatever we find!"}] },
  { title:"Borrowing a breast pump", desc:"Need a hospital-grade pump for a few weeks. Happy to sterilize.", type:"ASK", cat:"Kids", owner:"u11", comments:[{uid:"u5",text:"I have a Medela you can borrow. I'll drop it off."},{uid:"u12",text:"My wife might have one in the storage, let me check."}] },
  { title:"Used cargo bike for chores", desc:"Need to haul some heavy soil bags this weekend.", type:"ASK", cat:"Transport", owner:"u11", comments:[{uid:"u6",text:"I have one! It's at the bike kitchen, u10 has the key."},{uid:"u2",text:"You can use my van if the bike is too small."}] },
  { title:"Help with garden fence", desc:"My backyard fence is leaning. Need a hand stabilizing it.", type:"ASK", cat:"Home", owner:"u11", comments:[{uid:"u2",text:"I'll bring my drill and some brackets. Easy fix."},{uid:"u16",text:"I've got some spare wood that might help brace it."}] },
  { title:"Herbal Medicine Workshop", desc:"Making salves and tinctures from common neighborhood plants. All materials provided.", type:"JOIN", cat:"Health", owner:"u11", circleId:"c_zero", comments:[{uid:"u1",text:"This is so needed! I'll bring some jars."},{uid:"u5",text:"I can bring some beeswax from my uncle's farm."}] },

  // u12 Omar
  { title:"Football Skills Session", desc:"Sunday mornings at the park. Open to all kids ages 8-14.", type:"SHARE", cat:"Sports", owner:"u12", img:"https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400", comments:[{uid:"u8",text:"My son would love this! See you Sunday."},{uid:"u6",text:"I can help with coaching if you need a hand."}] },
  { title:"Free Haircuts for Seniors", desc:"Once a month I visit the local senior home. Happy to do a few extra.", type:"SHARE", cat:"Service", owner:"u12", comments:[{uid:"u4",text:"That's very kind of you, Omar. The Kiez is lucky to have you."},{uid:"u13",text:"I'll mention this at the library book club."}] },
  { title:"Portable BBQ Grill", desc:"Compact charcoal grill, perfect for the park or balcony.", type:"SHARE", cat:"Kitchen", owner:"u12", comments:[{uid:"u20",text:"Ideal for a summer evening! Can I borrow it Friday?"},{uid:"u9",text:"I'll bring the sausages!"}] },
  { title:"Borrowing a large cooler", desc:"Hosting a family picnic and need to keep drinks cold.", type:"ASK", cat:"Equipment", owner:"u12", comments:[{uid:"u8",text:"I have a huge one with wheels. Pick it up anytime."},{uid:"u18",text:"I've got one at the roastery you can use."}] },
  { title:"Truck for furniture move", desc:"Need to pick up a sofa from eBay Kleinanzeigen on Saturday.", type:"ASK", cat:"Transport", owner:"u12", comments:[{uid:"u2",text:"My van is available Saturday afternoon. I'll help you lift too."},{uid:"u10",text:"I can help with the straps and loading."}] },
  { title:"Advice on youth sports grants", desc:"Trying to get funding for the neighborhood team's new kits.", type:"ASK", cat:"Business", owner:"u12", comments:[{uid:"u18",text:"I know a local sponsor who might be interested!"},{uid:"u6",text:"I can help with the application forms."}] },
  { title:"Neighborhood Football Tournament", desc:"One-day friendly tournament for all ages. Referees, water, and snacks needed!", type:"JOIN", cat:"Sports", owner:"u12", comments:[{uid:"u15",text:"I'll organize the snacks and drinks table!"},{uid:"u7",text:"I'll provide some upbeat music for the intervals."}] },

  // u13 Petra
  { title:"Rare Art History Books", desc:"Beautiful coffee table books on Renaissance and Modern art.", type:"SHARE", cat:"Books", owner:"u13", img:"https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400", comments:[{uid:"u3",text:"The Renaissance one is a treasure! Can I borrow it?"},{uid:"u17",text:"Great for drawing inspiration. Would love to see them."}] },
  { title:"Street Library Curation", desc:"I manage the little library on the corner. Come for fresh picks!", type:"SHARE", cat:"Community", owner:"u13", comments:[{uid:"u4",text:"I dropped off some mystery novels yesterday."},{uid:"u8",text:"I have some photography mags to add."}] },
  { title:"Quiet Reading Space", desc:"My apartment is a library of its own. Welcome for quiet study.", type:"SHARE", cat:"Space", owner:"u13", comments:[{uid:"u3",text:"I need a calm place to sketch. This sounds perfect."},{uid:"u6",text:"Would love a change of scenery from my home office."}] },
  { title:"Help moving heavy bookshelves", desc:"Rearranging my home library. Need 2 people for 1 hour.", type:"ASK", cat:"Moving", owner:"u13", comments:[{uid:"u10",text:"I'm around this weekend. Happy to help."},{uid:"u2",text:"I'll bring my furniture sliders, makes it much easier."}] },
  { title:"Recommendations for a good binder", desc:"Need to repair some old books. Any local specialists?", type:"ASK", cat:"Skills", owner:"u13", comments:[{uid:"u16",text:"There's a great bookbinder on Pannierstr. I'll get the name."},{uid:"u17",text:"I know an artist who does traditional binding!"}] },
  { title:"Old laptop for the library", desc:"Need a simple machine for checking out books and cataloging.", type:"ASK", cat:"Tech", owner:"u13", comments:[{uid:"u6",text:"I have an old MacBook that still works great for that."},{uid:"u18",text:"Check the 'Tech for Good' circle, they might have a spare."}] },
  { title:"Street Library Maintenance Day", desc:"Painting, repairing, and organizing the neighborhood street libraries. Bring your favorite books to swap!", type:"JOIN", cat:"Community", owner:"u13", circleId:"c_books", comments:[{uid:"u4",text:"I'll bring my wood glue and some weatherproof paint."},{uid:"u17",text:"I'll design some cute 'Take a Book' stickers!"}] },

  // u14 Kenji
  { title:"Professional Knife Sharpening", desc:"Bring your kitchen knives. I'll give them a razor edge.", type:"SHARE", cat:"Service", owner:"u14", img:"https://images.unsplash.com/photo-1594498653385-d5172c532c00?w=400", comments:[{uid:"u9",text:"My chef's knife really needs this. When can I come?"},{uid:"u5",text:"Great for my bread knives too!"}] },
  { title:"Sushi Masterclass (Home edition)", desc:"Learn to roll maki and nigiri. 2-hour session, 4 people max.", type:"SHARE", cat:"Food", owner:"u14", comments:[{uid:"u20",text:"I'm in! Can I bring some prosecco to pair?"},{uid:"u3",text:"I'd love to learn the aesthetic side of sushi."}] },
  { title:"Martial Arts Basics", desc:"Intro to Aikido principles: balance and movement. Outdoors in the park.", type:"SHARE", cat:"Education", owner:"u14", comments:[{uid:"u12",text:"My kids would love to try this!"},{uid:"u6",text:"Great for focus and stress relief. Count me in."}] },
  { title:"Borrowing a large steamer", desc:"Want to make a big batch of steamed buns for a party.", type:"ASK", cat:"Kitchen", owner:"u14", comments:[{uid:"u9",text:"I have a professional bamboo one. It's yours!"},{uid:"u5",text:"I've got a metal insert for a large pot."}] },
  { title:"Local fish supplier tips", desc:"Looking for the freshest seasonal fish in Berlin. Any secrets?", type:"ASK", cat:"Food", owner:"u14", comments:[{uid:"u9",text:"Frischeparadies is the best, but expensive. I have a trade card."},{uid:"u1",text:"The Turkish market on Fridays has some hidden gems."}] },
  { title:"Help with German tax forms", desc:"Restaurant owner paperwork is confusing. Any finance-savvy neighbors?", type:"ASK", cat:"Business", owner:"u14", comments:[{uid:"u18",text:"I have a great accountant who specializes in gastro."},{uid:"u6",text:"I can help with the digital filing part."}] },
  { title:"Hinterhof Sushi Night", desc:"Communal sushi making and sharing. Everyone contributes to the ingredients cost. Fresh, fun, and local.", type:"JOIN", cat:"Food", owner:"u14", circleId:"c_cooking", comments:[{uid:"u20",text:"I'll handle the drinks and a tiramisu for dessert!"},{uid:"u1",text:"I'll bring fresh wasabi and pickled ginger."}] },

  // u15 Maria
  { title:"Salsa Dance Basics", desc:"Introductory steps for beginners. Fun, social, and active.", type:"SHARE", cat:"Arts", owner:"u15", img:"https://images.unsplash.com/photo-1545128485-c400e7702796?w=400", comments:[{uid:"u20",text:"I'll bring the music! Let's do this Saturday."},{uid:"u7",text:"I'd love to learn the rhythm side of it."}] },
  { title:"Spanish Conversation Practice", desc:"Improve your Spanish over coffee. All levels welcome.", type:"SHARE", cat:"Language", owner:"u15", comments:[{uid:"u12",text:"I need this for my next holiday!"},{uid:"u9",text:"I can trade for French lessons."}] },
  { title:"Colorful Dance Costumes", desc:"Spare costumes for parties or performances. Very vibrant!", type:"SHARE", cat:"Clothing", owner:"u15", comments:[{uid:"u19",text:"I'd love to see the fabrics! Maybe for a costume swap?"},{uid:"u17",text:"Great for photo shoots."}] },
  { title:"Borrowing a portable speaker", desc:"Need some music for a small outdoor dance rehearsal.", type:"ASK", cat:"Electronics", owner:"u15", comments:[{uid:"u6",text:"I have a JBL Boombox that's perfect. Yours for the day."},{uid:"u7",text:"I've got a smaller one if that's too big."}] },
  { title:"Recommendations for a pediatrician", desc:"New to the neighborhood, looking for a kind doctor for my kids.", type:"ASK", cat:"Health", owner:"u15", comments:[{uid:"u11",text:"Dr. Weber on Hobrechtstr is wonderful with children."},{uid:"u5",text:"We go to the one on Boxhagener Platz, very happy there."}] },
  { title:"Help with a broken stroller", desc:"Wheel is sticking and won't turn. Any handy neighbors?", type:"ASK", cat:"Repair", owner:"u15", comments:[{uid:"u10",text:"Bring it to the bike workshop Saturday. I'll fix it."},{uid:"u2",text:"Sounds like it just needs some WD-40. I'll come look."}] },
  { title:"Neighborhood Mural Project", desc:"Let's brighten up the grey wall in our Hinterhof. Paint and brushes provided. All artistic levels welcome!", type:"JOIN", cat:"Art", owner:"u15", circleId:"c_art", comments:[{uid:"u17",text:"I'll help with the sketching and outlines!"},{uid:"u3",text:"I've got some outdoor-grade paints to contribute."}] },

  // u16 Thomas
  { title:"Architecture Portfolios", desc:"Examples of sustainable urban living and modern design.", type:"SHARE", cat:"Education", owner:"u16", img:"https://images.unsplash.com/photo-1487958449913-2225e998d570?w=400", comments:[{uid:"u13",text:"These would be amazing for the library's design section."},{uid:"u6",text:"Would love to talk about smart home integration with you."}] },
  { title:"Advanced Woodworking Tools", desc:"Table saw, planer, and high-end chisels. For experienced users.", type:"SHARE", cat:"Tools", owner:"u16", comments:[{uid:"u2",text:"Your shop is my dream, Thomas. Can I come by Saturday?"},{uid:"u10",text:"I'd love to use the planer for a tabletop project."}] },
  { title:"Sustainable Home Design Advice", desc:"Thinking of renovating? I can give tips on materials and energy.", type:"SHARE", cat:"Service", owner:"u16", comments:[{uid:"u19",text:"I want to use only recycled materials for my shop. Advice?"},{uid:"u4",text:"I'm interested in solar panel options for my balcony."}] },
  { title:"Borrowing a large trailer", desc:"Need to pick up some heavy timber for a Kiez project.", type:"ASK", cat:"Transport", owner:"u16", comments:[{uid:"u2",text:"My van might be too small, but I know a guy with a flatbed."},{uid:"u10",text:"I have a heavy-duty bike trailer that can carry 80kg."}] },
  { title:"Help with local building permits", desc:"The paperwork for our community project is a nightmare. Any experts?", type:"ASK", cat:"Business", owner:"u16", comments:[{uid:"u18",text:"I went through this for the roastery. I'll share my notes."},{uid:"u4",text:"I have some old contacts at the Bauamt."}] },
  { title:"Scrap metal for a project", desc:"Looking for copper or steel offcuts for a garden sculpture.", type:"ASK", cat:"Materials", owner:"u16", comments:[{uid:"u10",text:"I have plenty of bike frame scraps at the workshop."},{uid:"u2",text:"Check the metal recycler on Weserstr, they are very friendly."}] },
  { title:"Raised Garden Bed Building Day", desc:"Let's build durable raised beds for our community garden using reclaimed timber. I'll lead the design and cutting.", type:"JOIN", cat:"Infrastructure", owner:"u16", circleId:"c_garden", comments:[{uid:"u1",text:"I've got the soil and seeds ready to go!"},{uid:"u5",text:"I'll bring snacks for the building crew."}] },

  // u17 Yuki
  { title:"Custom Illustration Commissions", desc:"I can draw your pet, your house, or a portrait of a loved one.", type:"SHARE", cat:"Arts", owner:"u17", img:"https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400", comments:[{uid:"u3",text:"Your style is so unique! Would love a portrait."},{uid:"u8",text:"Great for a birthday gift. I'll DM you."}] },
  { title:"Manga and Graphic Novel Collection", desc:"Hundreds of titles, mostly in Japanese and English.", type:"SHARE", cat:"Books", owner:"u17", comments:[{uid:"u13",text:"Can we host a manga night at the library?"},{uid:"u6",text:"I'm a huge Akira fan, do you have the full set?"}] },
  { title:"Digital Drawing Tablet Loan", desc:"Wacom Intuos Pro. For anyone wanting to try digital art.", type:"SHARE", cat:"Electronics", owner:"u17", comments:[{uid:"u3",text:"I've been wanting to try digital painting! Yes please."},{uid:"u6",text:"I can show you some great free drawing software for it."}] },
  { title:"Help with German pronunciation", desc:"My reading is okay, but I struggle with speaking clearly.", type:"ASK", cat:"Language", owner:"u17", comments:[{uid:"u4",text:"Come over for tea, we'll practice together."},{uid:"u13",text:"The book club is a great place to practice reading aloud!"}] },
  { title:"Cheap art supplies recommendation", desc:"Where do you buy your pens and paper in Berlin?", type:"ASK", cat:"Shopping", owner:"u17", comments:[{uid:"u3",text:"Modulor at Moritzplatz is the best! Very inspiring place."},{uid:"u15",text:"There's a hidden gem in Neukölln, I'll send you the address."}] },
  { title:"Quiet cafe with good WiFi", desc:"Looking for a place to work on my illustrations for a few hours.", type:"ASK", cat:"Space", owner:"u17", comments:[{uid:"u18",text:"My roastery is quiet on Tuesday mornings, and the coffee is great!"},{uid:"u9",text:"There's a cute French cafe on my street with a quiet back room."}] },
  { title:"Kiez Comic Anthology", desc:"Let's create a zine or comic book about our neighborhood stories. Illustrators and writers needed!", type:"JOIN", cat:"Culture", owner:"u17", circleId:"c_books", comments:[{uid:"u8",text:"I'll contribute some short stories based on my photos!"},{uid:"u13",text:"The library can print and distribute the final zine."}] },

  // u18 Bruno
  { title:"Fresh Roasted Coffee Beans", desc:"Roasted weekly in small batches. Whole bean or ground.", type:"SHARE", cat:"Food", owner:"u18", img:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400", comments:[{uid:"u20",text:"The smell from your roastery is the best part of my morning."},{uid:"u9",text:"I'll trade a tarte tatin for a bag of your beans!"}] },
  { title:"Home Barista Training", desc:"Learn how to pull the perfect shot and steam silky milk.", type:"SHARE", cat:"Education", owner:"u18", comments:[{uid:"u6",text:"My home espresso is always sour. Help!"},{uid:"u5",text:"I want to learn latte art for my brunch parties."}] },
  { title:"Coffee Grounds for Compost", desc:"Buckets of fresh grounds available every day. Great for the garden!", type:"SHARE", cat:"Garden", owner:"u18", comments:[{uid:"u1",text:"I'll take as much as you can give! My tomatoes love it."},{uid:"u11",text:"Great for the community garden too. I'll bring a bucket."}] },
  { title:"Borrowing a commercial grinder", desc:"Mine is down for maintenance. Need one for a few days.", type:"ASK", cat:"Equipment", owner:"u18", comments:[{uid:"u14",text:"I have an old Mazzer at the restaurant you can use."},{uid:"u9",text:"Let's ask the coffee shop on the corner, they are friendly."}] },
  { title:"Help with shop window display", desc:"Want to make the roastery front more inviting. Any creative eyes?", type:"ASK", cat:"Design", owner:"u18", comments:[{uid:"u17",text:"I'd love to draw some coffee-themed art for your window!"},{uid:"u19",text:"I can help with some sustainable fabric decorations."}] },
  { title:"Local marketing advice", desc:"How do I reach more people in our Kiez? Any tips?", type:"ASK", cat:"Business", owner:"u18", comments:[{uid:"u6",text:"I can help you set up a neighborhood newsletter."},{uid:"u5",text:"I'll mention you at the next block party planning meeting!"}] },
  { title:"Communal Coffee Morning", desc:"Sunday coffee and conversation at the roastery. Everyone welcome. Free coffee, bring your own snacks.", type:"JOIN", cat:"Community", owner:"u18", comments:[{uid:"u5",text:"I'll bring some fresh sourdough and jam!"},{uid:"u7",text:"I'll bring my guitar for some acoustic background music."}] },

  // u19 Freya
  { title:"Clothing Mending Workshop", desc:"Don't throw it away, fix it! I'll teach you basic sewing and patching.", type:"SHARE", cat:"Service", owner:"u19", img:"https://images.unsplash.com/photo-1528570916622-f7463bb27ef7?w=400", comments:[{uid:"u5",text:"I have a pile of jeans with holes. This is a lifesaver."},{uid:"u11",text:"Sustainability in action! I'll bring some herbal tea."}] },
  { title:"Sustainable Fabric Offcuts", desc:"Linen, organic cotton, wool. Great for small projects or quilting.", type:"SHARE", cat:"Materials", owner:"u19", comments:[{uid:"u3",text:"These would be amazing for my mixed-media art!"},{uid:"u17",text:"Can I use some for my zine covers?"}] },
  { title:"Ethical Fashion Guide", desc:"A list of my favorite local and global sustainable brands.", type:"SHARE", cat:"Education", owner:"u19", comments:[{uid:"u13",text:"Can we put a copy in the street library?"},{uid:"u15",text:"I'm trying to buy less fast fashion. This is great."}] },
  { title:"Borrowing a sewing machine", desc:"Mine is in the shop and I have an urgent order to finish.", type:"ASK", cat:"Electronics", owner:"u19", comments:[{uid:"u3",text:"I have a basic Singer you're welcome to use."},{uid:"u7",text:"I've got one too, it's quite old but works well."}] },
  { title:"Help with a website for my shop", desc:"I need a simple online presence to show my sustainable designs.", type:"ASK", cat:"Tech", owner:"u19", comments:[{uid:"u6",text:"I'll build you a simple portfolio site. Let's talk over coffee."},{uid:"u17",text:"I can help with the visual design and illustrations!"}] },
  { title:"Recommendations for a dry cleaner", desc:"Need to clean some delicate vintage silk. Any eco-friendly ones?", type:"ASK", cat:"Service", owner:"u19", comments:[{uid:"u16",text:"Green Clean on Sonnenallee is very reliable."},{uid:"u9",text:"I use one in Mitte, a bit far but worth it for silk."}] },
  { title:"Kiez Clothing Swap and Repair Café", desc:"Bring clothes to swap or learn how to fix your favorites. Let's reduce waste together!", type:"JOIN", cat:"Environment", owner:"u19", circleId:"c_zero", comments:[{uid:"u16",text:"I'll bring my workbench and some tools for general repairs!"},{uid:"u5",text:"I'll bring a basket of 'seconds' bread for everyone to snack on."}] },

  // u20 Dario
  { title:"Italian Cooking Secrets", desc:"Learn the art of authentic pasta and sauce. 3 generations of family recipes.", type:"SHARE", cat:"Food", owner:"u20", img:"https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=400", comments:[{uid:"u9",text:"Pasta vs Crêpes! Let's have a friendly culinary battle."},{uid:"u14",text:"I'd love to see how you approach noodle making."}] },
  { title:"Vinyl Listening Session", desc:"Come listen to some rare jazz and soul records. Coffee and comfy chairs provided.", type:"SHARE", cat:"Culture", owner:"u20", comments:[{uid:"u7",text:"Jazz and soul? My favorite! Tuesday afternoon?"},{uid:"u18",text:"I'll bring some fresh beans for the coffee side of things."}] },
  { title:"Vintage Record Player Loan", desc:"Technics SL-1200. Professional grade. Treat it with love.", type:"SHARE", cat:"Electronics", owner:"u20", comments:[{uid:"u7",text:"A classic! I'd love to hear my old classical records on this."},{uid:"u6",text:"I can help with the setup and calibration."}] },
  { title:"Borrowing a large pasta pot", desc:"Cooking for a big family gathering. Need a 10-liter pot.", type:"ASK", cat:"Kitchen", owner:"u20", comments:[{uid:"u9",text:"I have a huge one at the restaurant. It's yours!"},{uid:"u14",text:"I've got a large stockpot you can use."}] },
  { title:"Help with a leaking espresso machine", desc:"My vintage Gaggia is dripping. Any coffee tech experts?", type:"ASK", cat:"Repair", owner:"u20", comments:[{uid:"u18",text:"I fix these all the time at the roastery. Bring it by."},{uid:"u4",text:"I can look at the seals and gaskets with you."}] },
  { title:"Recommendations for a record shop", desc:"Looking for rare Italian soundtracks. Any hidden gems?", type:"ASK", cat:"Shopping", owner:"u20", comments:[{uid:"u7",text:"There's a tiny shop in Neukölln that specialize in OSTs!"},{uid:"u18",text:"I know a guy who has a private collection, I'll ask."}] },
  { title:"Community Pasta Night", desc:"Communal pasta making and feast. Bring your favorite sauce or a bottle of wine. Good music guaranteed.", type:"JOIN", cat:"Food", owner:"u20", circleId:"c_cooking", comments:[{uid:"u9",text:"I'll bring some French cheeses to follow the pasta!"},{uid:"u18",text:"I'll handle the after-dinner coffee service."}] },
];
